version: '3.8'

services:
  backend:
    build: .
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://admin:hE4BCg7pwG11@db/bookify
      - SECRET_KEY=k9yIxRqZg43lhML3uDzBaj_v-H1qgklTqDCkB_jvoDk
      - ALLOWED_ORIGINS=http://localhost:3000
    depends_on:
      - db
    env_file:
      - .env

  db:
    image: postgres:15
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: hE4BCg7pwG11
      POSTGRES_DB: bookify
    volumes:
      - postgres_data:/var/lib/postgresql/data


volumes:
  postgres_data: